### PR TITLE
Don't generate connect_xxx_notify for Read or ConstructOnly properties

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/issues/510

cc @antoyo

### CODE REVIEW

**Comment by EPashkin** [comment]
Network failure in all travis jobs :(

**Comment by antoyo** [comment]
Looks good to me.

**Comment by EPashkin** [comment]
@GuillaumeGomez Please, restart travis here

**Comment by GuillaumeGomez** [comment]
Done.

**Comment by EPashkin** [comment]
@GuillaumeGomez Thanks.

@antoyo CI passed.

**Comment by antoyo** [comment]
Do you want me to merge the PR?

**Comment by GuillaumeGomez** [comment]
Yup. You're the maintainer then if you're ok with the changes, you merge it. XD

**Pull request merged**
