### PR TITLE
Remove callback guard

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/glib/pull/250

cc @GuillaumeGomez, @antoyo

### CODE REVIEW

**Comment by EPashkin** [comment]
Only gio last

**Comment by antoyo** [comment]
Good for me.
Thank you.

**Comment by EPashkin** [comment]
It need single_verson_file too

**Comment by EPashkin** [comment]
Updated

**Comment by antoyo** [comment]
Is it ready to merge?

**Comment by EPashkin** [comment]
Yes

**Comment by antoyo** [comment]
Thanks.

**Pull request merged**
