### PR TITLE
Update gir-files submodule and regenerate

### PR DESCRIPTION
**Pull request by vhdirk**
This is mostly ok, apart from the constant ```WEBKIT_DOM_NODE_FILTER_SHOW_ALL```.  In the gir file, that is incorrectly defined as an int32, whereas it should be a uin32t or the value won't fit.
Seems like the gir tool has no way to fix that.

### CODE REVIEW

**Comment by antoyo** [comment]
It might be possible to fix [in the TOML config](https://github.com/gtk-rs/gir#the-api-mode-toml-config).
Look at the section about constants.

**Comment by vhdirk** [comment]
I checked that, but it seems it's not possible to overwrite the type of the constant. I'm not even sure if you can alter top-level constants.

**Comment by EPashkin** [comment]
Also need update .travis.toml
https://github.com/gtk-rs/gtk/blob/master/.travis.yml#L1
https://github.com/gtk-rs/gtk/blob/master/.travis.yml#L45

**Comment by antoyo** [comment]
Thanks.

**Comment by EPashkin** [comment]
@vhdirk Where I can find gir-files version, that you used for regen?
Submodule updated to 02dfee2cad98a73deaa8c07ea26ad64e0ead4de3
but changes says `from gir-files (https://github.com/gtk-rs/gir-files @ 02dfee2+)`
and 02dfee2 don't regens due many `GirXml: D:\eap\rust\0\gir-files\WebKit2-4.0.gir:3801:11: Missing type name`

**Comment by vhdirk** [comment]
Oh, sorry. I forgot that I initially modified ```WebKit2WebExtension-4.0.gir``` to get rid of those errors. I thought I had rolled that back and it just worked, but apparently not...
I could not figure out how to fix that with gir config. Seems to me that you can't alter the name of an output variable?

**Comment by EPashkin** [comment]
> I could not figure out how to fix that with gir config.
> Seems to me that you can't alter the name of an output variable?

Sorry, don't understand what you meant.

**Comment by EPashkin** [comment]
About your changes: can you add WIP PR with its to gir-files ?

**Comment by vhdirk** [comment]
Sure, I'll try to get that in tomorrow

**Comment by EPashkin** [comment]
@vhdirk Friendly reminder about gir-files

**Comment by vhdirk** [comment]
Also needs this commit: https://github.com/vhdirk/webkit2gtk-webextension-rs/commit/b7e56500766a2e422ded3a0ca3ac1a509a36c1dc

**Comment by vhdirk** [comment]
I've finally added all modifications to the gir files in a PR. See https://github.com/gtk-rs/gir-files/pull/33.

**Pull request merged**
