### PR TITLE
Add GitHub actions ci

### LINKED ISSUE #56: Migrate CI to github actions
Copy it from: https://github.com/gtk-rs/webkit2gtk-rs

### PR DESCRIPTION
**Pull request by matzipan**
Closes #56

### CODE REVIEW

**Comment by antoyo** [comment]
Am I missing something or are those actions have not been ran?

**Comment by matzipan** [comment]
I assume they need to be activated in the settings panel? I am very new to github actions.

**Comment by antoyo** [comment]
Ok, not sure what happened but when I created #59 with your commits, it triggers the CI.

It's weird because the settings say all users can start GitHub Actions.

**Comment by antoyo** [comment]
I'm closing this since it was added in #60.
Sorry for the delay.

**Pull request closed without merging**
